# Generated by Django 4.2.23 on 2025-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
