# Generated by Django 5.2.4 on 2025-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Complete', 'Complete'), ('Shipped Out', 'Shipped Out'), ('Cancelled', 'Cancelled')], default='Open', max_length=100),
        ),
    ]
